In [7]:
print("Welcome to Pizza Deliveries!")
size = input("What size pizza do you want ? S, M or L: ")
pepperoni = input("Do you want pepperoni on your pizza? Y or N : ")
extra_cheese = input("Do you want extra cheese? Y or N: ")

bill = 0

if size == "S":
    bill += 15
elif size == "M":
    bill += 20
elif size == 'L':
    bill += 25
else:
    print("You typed wrong inputs.")


if pepperoni == "Y":
    if size == "S":
        bill += 2
    else:
        bill += 3
        
if extra_cheese == "Y":
    bill += 1
    
print(f"Your final bill is: {bill}")

Welcome to Pizza Deliveries!


What size pizza do you want ? S, M or L:  L
Do you want pepperoni on your pizza? Y or N :  Y
Do you want extra cheese? Y or N:  N


Your final bill is: 28


In [25]:
print("Welcome to Treasure Islaand ")
print("Your mission is to find the trasure. ")
c1 = input("where do you want to go ? Type 'left' or 'right' . ")

if c1 == "left": 
    # will continue in the game 
    
    c2 = input("You came into a lake , there is an island in the middle of lake . Type 'wait' to wait for boat. Type 'swim' to swim in the lake")
    
    if c2 == "wait": # will continue in the game
        c3 = input("Here there are three colors select one color in this three colors then. Type'red' or 'blue' or 'yellow' . ")
        
        if c3 == "yellow":
            print("You found the treasure. You won!")
        elif c3 == "red":
            print("Burned by fire. Game Over!")
        elif c3 == "blue":
            print("Eaten by beasts. Game over! ")
        else:
            print("Your room doesnot exits! ")
        
    else:
        print("Attacked by trout. Game over!")
else:
    print("you fell in a hole. Game over!")
    

Welcome to Treasure Islaand 
Your mission is to find the trasure. 


where do you want to go ? Type 'left' or 'right' .  left
You came into a lake , there is an island in the middle of lake . Type 'wait' to wait for boat. Type 'swim' to swim in the lake wait
Here there are three colors select one color in this three colors then. Type'red' or 'blue' or 'yellow' .  yellow


You found the treasure. You won!


In [6]:
import random

random_number_0_to_1 = random.random()

print(random_number_0_to_1)

0.10838988466107147


In [3]:
scissors = '''
   -------
---    ---)
           ----)
         --------)
         (-----)
      .--(----)
------
'''
print(scissors)


   -------
---    ---)
           ----)
         --------)
         (-----)
      .--(----)
------



In [17]:
# If- Else program
import random
user_choice = int(input("what do you choose ? Type 0 for   Rock, 1 for paper, 2 for scissors.\n"))

computer_choice = random.randint(0 , 2)
print(f"Computer choose {computer_choice}")

if user_choice == 0 and computer_choice == 2:
    print("You win")
elif computer_choice > user_choice:
    print("You lose")
elif  computer_choice == user_choice:
    print("It's draw!")
else:
    print("You typed a invalid number")

what do you choose ? Type 0 for   Rock, 1 for paper, 2 for scissors.
 0


Computer choose 1
You lose


In [9]:
student_score = [20,152,125,30,145,24,78,25,132,158,178,199,200,192,56,58,79,99]

max_score = 0
for score in student_score:
    if score > max_score:
        max_score = score
print(max_score)

200


In [29]:
sum = 0
for number in range(1,101):
    sum += number 
print(sum)

5050


In [71]:
for i in range(1,101):
    if i % 3 == 0 and i % 5== 0:
        print("fizz Buzz")
    elif i % 5 == 0:
        print("Buzz")
    elif i % 3 == 0:
        print("Fizz")
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
fizz Buzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
fizz Buzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
fizz Buzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
fizz Buzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
fizz Buzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
fizz Buzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [10]:
n = int(input()) 

for i in range(1, n + 1):
    print(i, end="")


 3


123

In [1]:
from sklearn.metrics import mean_absolute_error
y_true = [3,-0.5,2,7]
y_pred = [2.5,0.0,2,8]
print("Mean Absolute Error: " , mean_absolute_error(y_true,y_pred))

Mean Absolute Error:  0.5


In [15]:
fruits = ["Banana","apple","cherry"]
index=0
while index<len(fruits):
    print(fruits[index])
    index+=1

Banana
apple
cherry


In [ ]:
list_name = []
if __name__ == '__main__':
    N = int(input())
    list_name.insert(0,"e")
    list_name.remove("e")
    list_name.append("e")
    list_name.sort()
    list_name.pop(0)
    list_name.reverse()
    print(list_name)

In [19]:
# Hangam program

import random

word_list = ["ambulance", "barbon" , "camel",  "Nuthalapati", "Vikas", "Mahesh"]
lives = 6 

chosen_word = random.choice(word_list)

place_holder = ""
for position in range(1, 6):
    place_holder += "_"
print(place_holder)

game_over = False
correct_letters = []

while not game_over:
    
    print("*********************<lives>/6 Lives Left**************************")
    guess = input("Guess the letter: ").lower()

    if guess in correct_letters:
        print(f"You've already guessed {guess}")
        
    display = ""

    for letter in chosen_word:
        if letter == guess:
            display += letter
            correct_letters.append(guess)
        elif letter in correct_letters:
            display += letter
        else:
            display += "_"
        
    print(display)

    
    if guess not in chosen_word:
        lives -= 1
        print(f"You guessed {guess},that's not in the word. You lose a life.")
        
        if lives == 0:
            game_over = True
            print(f"******************IT WAS {chosen_word} ! You Loss*****************")

    if "_" not in display:
        game_over = True
        print("***************You Win*****************")

    print(lives)

_____
*********************<lives>/6 Lives Left**************************


Guess the letter:  a


a____a___
6
*********************<lives>/6 Lives Left**************************


Guess the letter:  m


am___a___
6
*********************<lives>/6 Lives Left**************************


Guess the letter:  b


amb__a___
6
*********************<lives>/6 Lives Left**************************


Guess the letter:  l


amb_la___
6
*********************<lives>/6 Lives Left**************************


Guess the letter:  n


amb_lan__
6
*********************<lives>/6 Lives Left**************************


Guess the letter:  c


amb_lanc_
6
*********************<lives>/6 Lives Left**************************


Guess the letter:  e


amb_lance
6
*********************<lives>/6 Lives Left**************************


Guess the letter:  u


ambulance
***************You Win*****************
6


In [63]:
# Function
def greet():
    print("Nuthalapati ")
    print("Mahesh")
    print("Vikas")
greet()

Nuthalapati 
Mahesh
Vikas


In [65]:
# Function with inputs
def greet(name):
    print(f" Hello {name}")
greet("Mahesh")

 Hello Mahesh


In [67]:
# Function with inputs
def life_in_weeks(age):
    total_weeks = 90*52
    weeks_lived = age*52
    weeks_left = total_weeks - weeks_lived
    print(f"You have {weeks_left} weeks left.")
life_in_weeks(25)

You have 3380 weeks left.


In [69]:
# Function with inputs and positional arguments
def greet(name, location):
    print(f" Hello {name}")
    print(f"What is your name is {location}")
greet("Vikas","Uppalapadu")

 Hello Vikas
What is your name is Uppalapadu


In [79]:
# Function with inputs and keyword arguments
def greet(name, location):
    print(f" Hello {name}")
    print(f"What is your location name is {location}")
greet(name= "Vikas", location= "Uppalapadu")
greet(location= "NRT", name="Mahesh")

 Hello Vikas
What is your location name is Uppalapadu
 Hello Mahesh
What is your location name is NRT


In [95]:
def calculate_love_score(name1,name2):
    both_names = (name1+name2)
    true_count = both_names.count("t")+both_names.count("r")+both_names.count("u")+both_names.count("e")
    love_count = both_names.count("l")+both_names.count("o")+both_names.count("v")+both_names.count("e")
    score = int(str(true_count) + str(love_count))
    print(score)
calculate_love_score("Kanye West", "Kim Kardashian")

42


In [99]:
alphabet = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

direction = input("Type 'encode' to encrypt type 'decode' to decrypt:\n").lower()
text = input("Type your message:\n").lower()
shift = int(input("Type the shift number"))

def encrypt(original_text, shift_amount):
    

26


Type 'encode' to encrypt type 'decode' to decrypt:
 hi
Type your message:
 h
Type the shift number 2


In [17]:
student_scores = {
    'Harry': 88,
    'Ron': 78,
    'Hermione': 95,
    'Draco': 75,
    'Neville': 60
}

student_grades = {}

for student,scores in student_scores.items() :
    if 91 <= scores <=100:
        student_grades[student] = "outstanding"
    elif 81 <= scores <=90:
        student_grades[student] = "Exceeds Expectations"
    elif 71 <= scores <=80:
        student_grades[student] ="Acceptable"
    else:
        student_grades[student] ="Fail"
print(student_grades)

{'Harry': 'Exceeds Expectations', 'Ron': 'Acceptable', 'Hermione': 'outstanding', 'Draco': 'Acceptable', 'Neville': 'Fail'}


In [47]:
capitals = {
    "AP" : "Amaravathi",
    "TS" : "Hyderabad"
}

travelled = {
    "AP" : ['Ktp', "vizag", "srisailam"],
    "TS" : ["hyd", "charminar"]
}
print(travelled["AP"][1])

vizag


In [61]:
def my_function():
    result = 3 * 2
    return result
my_function()

6

In [7]:
def is_leap_year(year):
    # Write your code here. 
    # Don't change the function name.
    return(year % 4 == 0 and year % 100 != 0 or year % 400 == 0)
is_leap_year(2024)

True

In [31]:
def is_leap_year(year):
    if year % 4 == 0 and year % 100 != 0 or year % 400 == 0:
        print("leap year")
    else:
        print("Not a leap year")
is_leap_year(2004)

leap year


In [9]:
def my_function(a):
    if a < 40:
        return
        print("Terrible")
    if a < 80:
        return "Pass"
    else:
        return "Great"
print(my_function(25))

None


### Prime numbers

In [21]:
num = (12,15,7,2,3,8,9,257,752,16,4,19,97)
for i in num:
    if num == 0:
        print("not prime")
        break;
else:
    print("prime")

prime


In [37]:
num = (12, 15, 7, 2, 3, 8, 9, 257, 752, 16, 4, 19, 97)

for n in num:
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            print("not prime")
            break
else:
    print("prime")


not prime
not prime
not prime
not prime
not prime
not prime
not prime
prime


### Array

In [9]:
from array import *

vals = [1, 2, 3, 4, 5]
vals.reverse()
print(vals)
for i in range(5):
    print(vals[i])

[5, 4, 3, 2, 1]
5
4
3
2
1


In [15]:
from numpy import *

arr = array([1,2,3,4,5],float)
print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5.]


In [13]:
# dimensional arrays
from numpy import *
arr1 = array([
    [1,2,3,4],
    [5,6,7,8]
])
print(arr1)

arr2 = arr1.flatten()
print(arr2)

arr3 = arr2.reshape(2,2,2)
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### functions

In [37]:
def add_sub(x,y):
    c= x+y
    d= x-y
    return c,d
add_sub(5,4)

(9, 1)

In [39]:
# function argumnets
def greet(name):
    print("hello" , name)
greet("vikas")

hello vikas


In [71]:
# types of function arguments
 # 1.positional
 # 2.keyword
 # 3.default
 # 4.variable-length , 4.1 = args ,4.2 = kwargs

# 1
def person(name,age):
    print(name)
    print(age)
person("vikas",20)

# 2
def person(name,age):
    print(name)
    print(age)
person(age=20,name="vikas")

# 3
def person(name,age=18):
    print(name)
    print(age)
person("vikas")

# 4.1
def sum(a,*b):
    c = a
    for i in b:
        c = c + i
    print(c)
sum(20,15,6,23,14)

# 4.2 kwargs
def people(name,**data):
    print(name)
    for i,j in data.items():
        print(i,j)
people("vikas",age=19,city="nrt",mob=9876543210)


vikas
20
vikas
20
vikas
18
78
vikas
age 19
city nrt
mob 9876543210


In [89]:
# scope
a = 10 
print(id(a))
def number():
    a = 9
    
    x = globals()['a']
    print(id(x))
    print("inside",a)
    
    globals()['a'] = 15
    
number()

140721317161688
140721317161688
inside 9


In [100]:
# fibonacci sequence
def fib(n):
    a=0
    b=1
    if n==b:
        print(a)
    elif n<a:
        print("enter valid nunber")
    else:
        print(a)
        print(b)
    for i in range(2,n):
        f=0
        f=a+b
        a=b
        b=f
        if f<100:
            print(f)
user_input = int(input("enter the value:"))
fib(user_input)

enter the value: 100


0
1
1
2
3
5
8
13
21
34
55
89


In [110]:
# factorial - 5!=5*4*3*2*1
def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    return f
x = 6
result = fact(x)
print(result)

720


In [1]:
# recursion
import sys
sys.setrecursionlimit(2000) # sys is used for the deeper than the default limit

print(sys.getrecursionlimit())
i=0
def greet():
    global i
    i+=1
    print("hello",i)
    greet()
greet()


2000
hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
hello 7
hello 8
hello 9
hello 10
hello 11
hello 12
hello 13
hello 14
hello 15
hello 16
hello 17
hello 18
hello 19
hello 20
hello 21
hello 22
hello 23
hello 24
hello 25
hello 26
hello 27
hello 28
hello 29
hello 30
hello 31
hello 32
hello 33
hello 34
hello 35
hello 36
hello 37
hello 38
hello 39
hello 40
hello 41
hello 42
hello 43
hello 44
hello 45
hello 46
hello 47
hello 48
hello 49
hello 50
hello 51
hello 52
hello 53
hello 54
hello 55
hello 56
hello 57
hello 58
hello 59
hello 60
hello 61
hello 62
hello 63
hello 64
hello 65
hello 66
hello 67
hello 68
hello 69
hello 70
hello 71
hello 72
hello 73
hello 74
hello 75
hello 76
hello 77
hello 78
hello 79
hello 80
hello 81
hello 82
hello 83
hello 84
hello 85
hello 86
hello 87
hello 88
hello 89
hello 90
hello 91
hello 92
hello 93
hello 94
hello 95
hello 96
hello 97
hello 98
hello 99
hello 100
hello 101
hello 102
hello 103
hello 104
hello 105
hello 106
hello 107
hello 108
hello 109
hello 110
hel

RecursionError: maximum recursion depth exceeded

In [11]:
# factorial using recursion
def fact(n):
    if n==0:
        return 1
    return n * fact(n-1)

print(fact(5))

120


In [41]:
# lambda
v = lambda a,b: a+b
print(v(2,7))

9


In [37]:
# lambda types filter , map , reduce
from functools import reduce 
nums = [1,2,3,6,5,4,9,8,7,0]
evens = list(filter(lambda n : n % 2 == 0, nums))
doubles = list(map(lambda n : n*2, evens))
sum = reduce(lambda a,b: a+b, doubles)
print(evens)
print(doubles)
print(sum)

[2, 6, 4, 8, 0]
[4, 12, 8, 16, 0]
40


In [3]:
# decorators
def div(a,b):
    print(a/b)
def smart_div(func):
    def inner(a,b):
        if a<b:
            a,b = b,a
        return func(a,b)
    return inner
div_1 = smart_div(div)
div_1(4,8)

2.0


In [5]:
print(__name__)

__main__


### OOPS (Object Oriented Programming System )

In [9]:
# object , class, encapsulation, abstraction, polymorphismm
# class - design or blue print
# object - instance or real entities

class computer:

    def config(self):
        print("i7, 16gb, 1TB")

comp1 = computer()

computer.config(comp1)

comp1.config() # this is the actual calling of an object

i7, 16gb, 1TB
i7, 16gb, 1TB


In [13]:
# __init__ function
class computer:

    def __init__(self,cpu,ram):
        self.cpu = cpu
        self.ram = ram
    def config(self):
        print("config is ", self.cpu, self.ram)

comp1= computer("i5",16)
comp2 = computer("ryzen",8)
comp1.config()
comp2.config()

config is  i5 16
config is  ryzen 8


In [23]:
# conductor , self and comparing objects
class Computer:
    pass


c1 = Computer()

print(id(c1))
# not finished

2746033645776


In [35]:
# types of variables in oops 1. instance and 2. class (static) know about namespace
class Car:

    wheels = 4        #this is the class (static) variable

    def __init__(self):
        self.mil = 30            # this is the instance variable
        self.com = "BMW"         # this is also instance variable

c1 = Car()
c2 = Car()

c1.mil = 25
Car.wheels = 5

print(c1.com,c1.mil,c1.wheels)
print(c2.com,c2.mil,c2.wheels)

BMW 25 5
BMW 30 5


In [44]:
# types of methods in oops 1. instance method , 2. class method , 3. static method
# instance types are 1.Accessor fetch the value 2.mutator is to modify
# if we work with instance we use self
# if we work with class we use cls and @classmethod
# static method is not used the class or instance methods it seperate or for the extra work
# we use @staticmethod for the static method

In [46]:
# types of methods
class student:
    school = "MRUH"
    
    def __init__(self,m1,m2,m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
        
    def avg(self):
        return(self.m1+self.m2+self.m3)/3

    def get_m1(self):
        return self.m1

    def set_m1(self,value):
        self.m1 = value

    @classmethod
    def getschool(cls):
        return cls.school

    @staticmethod
    def info():
        print("This is student class.. in the abc method")

s1 = student(68,98,85)
s2 = student(45,65,85)

print(s1.avg())
print(student.getschool())

student.info()

83.66666666666667
MRUH
This is student class.. in the abc method


In [3]:
# inner class
class Student:

    def __init__(self,name,rollno):
        self.name = name
        self.rollno = rollno
        self.lap = self.Laptop()

    def show(self):
        print(self.name,self.rollno)
        self.lap.show()


    class Laptop:

        def __init__(self):
            self.brand = "ACER"
            self.cpu = "i7"
            self.ram = 16
        def show(self):
            print(self.brand,self.cpu,self.ram)

s1 = Student("vikas",2)
s2 = Student("mahesh",1)

s1.show()
s2.show()

vikas 2
ACER i7 16
mahesh 1
ACER i7 16


### Inheritance

In [15]:
# inheritance  three types of inheritance 1.single level 2.multiple 3.multi level
# type-1
# single-level inheritance
class A:
    def feature1(self):
        print("Feature 1 is working")

class B(A):
    def feature2(self):
        print("Feature 2 is working")
        x = B()
x.feature1()
x.feature2()

Feature 1 is working
Feature 2 is working


In [17]:
# type-2
# multiple inheritance
class A:
    def feature1(self):
        print("Feature 1 is working")

class B:
    def feature2(self):
        print("Feature 2 is working")
    
class C(A,B):
    def feature3(self):
        print("Feature 3 is working")
x = C()
x.feature1()
x.feature2()
x.feature3()

Feature 1 is working
Feature 2 is working
Feature 3 is working


In [13]:
# type-3
# multi-level inheritance
class A:
    def feature1(self):
        print("Feature 1 is working")

class B(A):
    def feature2(self):
        print("Feature 2 is working")
    
class C(B):
    def feature3(self):
        print("Feature 3 is working")

x = B()
x.feature1()
x.feature2()
y = C()
y.feature1()
y.feature2()
y.feature3()

Feature 1 is working
Feature 2 is working
Feature 1 is working
Feature 2 is working
Feature 3 is working


### polymorphism in OOPs

In [4]:
# in polymorphism is of 1.duck typing  2.operator ooverloading 3. method overloading 4.method overriding
# 1. Duck Typing
class Pycharm:

    def execute(self):
        print("compiling")
        print("running")

class myeditior:

    def execute(self):
        print("Spell Check")
        print("convertion check")
        print("compiling")
        print("running")

class Laptop:

    def code(self,ide):
        ide.execute()

ide = myeditior()
lap1 = Laptop()
lap1.code(ide)

Spell Check
convertion check
compiling
running


In [1]:
# 2. Operator Overloading
class Student:

    def __init__(self,m1,m2):
        self.m1 = m1
        self.m2 = m2

    def __add__(self, other):
        m1 = self.m1+other.m1
        m2 = self.m2 + other.m2
        s3 = Student(m1,m2)

        return s3

    def __gt__(self, other):
        r1 = self.m1+self.m2
        r2 = other.m1+other.m2
        if r1 > r2:
            return True
        else:
            return False

    def __str__(self):
        return "{} {} ".format(self.m1, self.m2)
    


s1 = Student(50,65)
s2 = Student(55,60)

s3 = s1 + s2

if s1 > s2:
    print("s1 wins")
else:
    print("s2 wins")

print(s1.__str__())

s2 wins
50 65 


In [1]:
# 3. Method overloading and method ooverriding
# Method Overloading
class Student:

    def __init__(self,m1,m2):
        self.m1 = m1
        self.m2 = m2
    def sum(self,a=None,b=None,c=None):
        if a!=None and b !=None and c!=None:
            s = a+b+c
        elif a!=None and b!=None:
            s = a+b
        else:
            s = a

        return s


s1 = Student(58,62)
print(s1.sum(2,1,4))

7


In [6]:
# Method Overriding
class A:
    def show(self):
        print("In A")
class B(A):
    def show(self):
        print("In B")

x = A()
y = B()
y.show()

In B


In [5]:
# Iterator
class FirstTen:

    def __init__(self):
        self.num = 1

    def __iter__(self):
        return self

    def __next__(self):

        if self.num <= 10:
            val = self.num
            self.num += 1

            return val

        else:
            raise StopIteration

values = FirstTen()

print(next(values))
for i in values:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [12]:
# Generators  - we use yield keyword


def topten():

    n = 1

    while n<=10:
        sq = n*n
        yield sq
        n += 1



values = topten()

for i in values:
    print(i)

1
4
9
16
25
36
49
64
81
100


### Exception Handling

In [5]:
# 1. Compile time error  -  it is an syntax error
# 2. Logical error  -  wrong output
# 3. Run time error  -  divide by zero

In [43]:
# Exception
a = 5
b = 2

try:
    print("Resource open")
    x = a/b
    print(x)
    k = int(input("Enter a number"))
    print(k)
    print(x/k)

except ZeroDivisionError as e:
    print("you can't divide with 0")

except ValueError as e:
    print("Inavalid Output")

except:
    print("something went wrong")

finally:
    print("Resourse Closed")

Resource open
2.5


Enter a number 2


2
1.25
Resourse Closed


### MultiThreading

In [49]:
from threading import *
from time import *

class Hello(Thread):
    def run(self):
        for i in range(5):
            print("Hello")
            sleep(1)

class Hi(Thread):
    def run(self):
        for i in range(5):
            print("Hi")
            sleep(1)

x = Hello()
y = Hi()

x.start()
sleep(0.1)
y.start()

x.join()
y.join()

print("Bye ")

Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Bye 


In [92]:
# Linear Search in while loop
pos = -1

def search(list,n):
    i=0
    
    while i<len(list):
        if list[i] == n:
            globals() ['pos'] = i
            return True;
        i = i +1
    return False;

list = [5,9,6,4,3,2,1,7]
n = 2

if search(list, n):
    print("Found at",pos+1)
else:
    print("Not Found")

Found at 6


In [98]:
# Linear Search in for loop
pos = -1
def search(list,n):
    i=0
    
    for i in range(len(list)):
        if list[i] == n:
            globals() ['pos'] = i
            return True

list = [5,9,6,4,3,2,1,7]
n = 2

if search(list, n):
    print("Found at " , pos)
else:
    print("Not Found")

Found at  5


In [7]:
# Binary Search
pos = -1
def search(list,n):
    l = 0
    u = len(list)-1

    while l <= u :
        mid = (l+u) // 2

        if list[mid] == n:
            globals() ['pos'] = mid
            return True

        else:
            if list[mid] < n:
                l = mid+1
            else:
                u = mid-1

    return False

list = [1,5,9,8,10,123,145,257,527,752]
n = 525

if search(list, n):
    print("Found at " , pos+1)
else:
    print("Not Found")

Not Found


In [32]:
# Bubble sort
nums = [5,1,4,3,8,6,2,9,0,7]

def sort(nums):

    for i in range(len(nums)-1,0,-1):
        for j in range(i):
            if nums[j]>nums[j+1]:
                temp = nums[j]
                nums[j] = nums[j+1]
                nums[j+1] = temp

sort(nums)
print(nums)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [62]:
# Selection sort
nums = [5,8,6,7,10,3]

def sort(nums):

    for i in range(5):
        minpos = i
        for j in range(i,6):
            if nums[j] < nums[minpos]:
                minpos = j


                temp = nums[i]
                nums[i] = nums[minpos]
                nums[minpos] = temp
                
sort(nums)
print(nums)

[3, 5, 7, 6, 8, 10]


In [15]:
# selection sort
nums = [5,8,6,1,0,7,2]

def sort(nums):
    n = len(nums)

    for i in range(n):
        minpos = i
        for j in range(i,n):
            if nums[j] < nums[minpos]:
                minpos = j

            if minpos != i:
                temp = nums[i]
                nums[i] = nums[minpos]
                nums[minpos] = temp

sort(nums)
print(nums)

[0, 1, 2, 5, 6, 7, 8]
